/*
 *  This program is a part of the IoTa project.
 *
 *  Copyright © 2008-2012  Université de Caen Basse-Normandie, GREYC
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  <http://www.gnu.org/licenses/>
 *
 *  See AUTHORS for a list of contributors.
 */
package fr.unicaen.iota.auth;

import java.util.Date;
import java.util.Set;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 *
 * This is an object that contains data related to the partner table. Do not
 * modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class table="partner"
 */
public class Partner {

    public static String PROP_ACTIVE = "Active";
    public static String PROP_DATE = "Date";
    public static String PROP_SERVICE_ID = "ServiceID";
    public static String PROP_SERVICE_ADDRESS = "ServiceAddress";
    public static String PROP_SERVICE_TYPE = "ServiceType";
    public static String PROP_ID = "Id";
    public static String PROP_PARTNER_I_D = "PartnerID";
    // primary key
    private Integer _id;
    // fields
    private boolean _active;
    private String _partnerID;
    private String _serviceID;
    private Date _date;
    private String _serviceType;
    private String _serviceAddress;
    // collections
    private Set _userSet;
    private Set _scSet;
    private Set _scassociationSet;

    // constructors
    public Partner() {
        initialize();
    }

    /**
     * Constructor for primary key
     */
    public Partner(Integer _id) {
        this.setId(_id);
        initialize();
    }

    /**
     * Constructor for required fields
     */
    public Partner(Integer _id, boolean _active, String _partnerID, java.util.Date _date, String _serviceID, String _serviceType, String _serviceAddress) {
        this.setId(_id);
        this.setActive(_active);
        this.setPartnerID(_partnerID);
        this.setDate(_date);
        this.setServiceID(_serviceID);
        this.setServiceType(_serviceType);
        this.setServiceAddress(_serviceAddress);
        initialize();
    }

    protected void initialize() {
    }

    /**
     * Return the unique identifier of this class @hibernate.id
     * generator-class="vm" column="ID"
     */
    public Integer getId() {
        return _id;
    }

    /**
     * Set the unique identifier of this class
     *
     * @param _id the new ID
     */
    public void setId(Integer _id) {
        this._id = _id;
    }

    /**
     * Return the value associated with the column: active
     */
    public boolean isActive() {
        return _active;
    }

    /**
     * Set the value related to the column: active
     *
     * @param _active the active value
     */
    public void setActive(boolean _active) {
        this._active = _active;
    }

    /**
     * Return the value associated with the column: partnerID
     */
    public String getPartnerID() {
        return _partnerID;
    }

    /**
     * Set the value related to the column: partnerID
     *
     * @param _partnerID the partnerID value
     */
    public void setPartnerID(String _partnerID) {
        this._partnerID = _partnerID;
    }

    /**
     * Return the value associated with the column: date
     */
    public java.util.Date getDate() {
        return _date;
    }

    /**
     * Set the value related to the column: date
     *
     * @param _date the date value
     */
    public void setDate(java.util.Date _date) {
        this._date = _date;
    }

    public String getServiceID() {
        return _serviceID;
    }

    public void setServiceID(String _serviceID) {
        this._serviceID = _serviceID;
    }

    /**
     * Return the value associated with the column: serviceType
     */
    public String getServiceType() {
        return _serviceType;
    }

    /**
     * Set the value related to the column: serviceType
     *
     * @param _serviceType the serviceType value
     */
    public void setServiceType(String _serviceType) {
        this._serviceType = _serviceType;
    }

    /**
     * Return the value associated with the column: serviceAddress
     */
    public String getServiceAddress() {
        return _serviceAddress;
    }

    /**
     * Set the value related to the column: serviceAddress
     *
     * @param _serviceAddress the serviceAddress value
     */
    public void setServiceAddress(String _serviceAddress) {
        this._serviceAddress = _serviceAddress;
    }

    /**
     * Return the value associated with the column: UserSet
     */
    public java.util.Set getUserSet() {
        return this._userSet;
    }

    /**
     * Set the value related to the column: UserSet
     *
     * @param _userSet the UserSet value
     */
    public void setUserSet(java.util.Set _userSet) {
        this._userSet = _userSet;
    }

    public void addToUserSet(Object obj) {
        if (null == this._userSet) {
            this._userSet = new java.util.HashSet();
        }
        this._userSet.add(obj);
    }

    /**
     * Return the value associated with the column: ScSet
     */
    public java.util.Set getScSet() {
        return this._scSet;
    }

    /**
     * Set the value related to the column: ScSet
     *
     * @param _scSet the ScSet value
     */
    public void setScSet(java.util.Set _scSet) {
        this._scSet = _scSet;
    }

    public void addToScSet(Object obj) {
        if (null == this._scSet) {
            this._scSet = new java.util.HashSet();
        }
        this._scSet.add(obj);
    }

    /**
     * Return the value associated with the column: ScassociationSet
     */
    public java.util.Set getScassociationSet() {
        return this._scassociationSet;
    }

    /**
     * Set the value related to the column: ScassociationSet
     *
     * @param _scassociationSet the ScassociationSet value
     */
    public void setScassociationSet(java.util.Set _scassociationSet) {
        this._scassociationSet = _scassociationSet;
    }

    public void addToScassociationSet(Object obj) {
        if (null == this._scassociationSet) {
            this._scassociationSet = new java.util.HashSet();
        }
        this._scassociationSet.add(obj);
    }

    @Override
    public String toString() {
        return super.toString();
    }
}