/*
 *  This program is a part of the IoTa project.
 *
 *  Copyright © 2008-2012  Université de Caen Basse-Normandie, GREYC
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, version 2 of the License.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  <http://www.gnu.org/licenses/>
 *
 *  See AUTHORS for a list of contributors.
 */
package fr.unicaen.iota.simulator.gui;

import fr.unicaen.iota.simulator.app.Trash;
import fr.unicaen.iota.simulator.app.TrashListener;
import java.awt.Color;
import java.util.Collection;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 */
public class TrashGUI extends javax.swing.JFrame implements TrashListener {

    private int currentIndex = 0;

    public static void main(String[] argv) {
        new TrashGUI().setVisible(true);
    }

    /** Creates new form delettedProducts */
    public TrashGUI() {
        initComponents();
        initSelfComponents();
        Trash.getInstance().addTrashListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void initSelfComponents() {
        this.setSize(400, 400);
        this.setTitle("Trash");
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                //                new Object[][]{{1+"","urn:epc:id:sgtin:50000.00001.1287156324085",""}},
                new Object[][]{},
                new String[]{"id", "EPC", ""}));
        jTable1.getColumnModel().getColumn(1).setWidth(20);
        TableColumn column = jTable1.getColumnModel().getColumn(0);
        column.setMaxWidth(30);
        column.setPreferredWidth(30);

        TableColumn column1 = jTable1.getColumnModel().getColumn(2);
        column1.setMaxWidth(20);
        column1.setPreferredWidth(20);

        column1.setCellEditor(new CellDetailsEditor(this));
        column1.setCellRenderer(new DetailsCellRenderer("play.png"));

        this.getContentPane().setBackground(Color.WHITE);
        jScrollPane1.setBackground(Color.WHITE);
        jTable1.setBackground(Color.WHITE);
    }

    @Override
    public void TrashEvt(Collection<String> epcList) {
        for (String epc : epcList) {
            currentIndex++;
            ((DefaultTableModel) jTable1.getModel()).addRow(new String[]{currentIndex + "", epc, ""});
        }
    }
}
